import os
from getpass import getpass

print("---------------------------------------------------------------------------------------------------------")
cloud = int(input("Kindly Select Your Cloud(1/2/3):\n\n1.MICROSOFT AZURE        2.AWS        3.GOOGLE CLOUD \n\nYour input: "))
print("---------------------------------------------------------------------------------------------------------")
centralizedpat = getpass("Enter Insight Central repo PAT token: ")
if cloud == 1:
    if os.path.exists("onboard_script"): os.system("rm -rf onboard_script")
    os.system(f"git clone --sparse --depth=1 https://{centralizedpat}@dev.azure.com/nsitmspdevops/Insight%20CMP%20Centralized%20Repository/_git/onboard_script")
    # os.system(f"git clone --sparse --depth=1 https://{centralizedpat}@dev.azure.com/nsitmspdevops/Development-Insight%20CMP%20Centralized%20Repository/_git/onboard_script")
    cwd_home = os.getcwd()
    os.chdir(f"{cwd_home}/onboard_script")
    if os.path.exists("azure-pipelines.yml"): os.system("rm azure-pipelines.yml")
    if os.path.exists("aws.py"): os.system("rm aws.py")
    if os.path.exists("gcp.py"): os.system("rm gcp.py")
    exec(open("azure.py").read())
    os.chdir(f"{cwd_home}")
    print(cwd_home)
    if os.path.exists("onboard_script"): os.system("rm -rf onboard_script")
    if os.path.exists("azure_onboard"): os.system("rm -rf azure_onboard")
    if os.path.exists("aws_onboard"): os.system("rm -rf aws_onboard")
    if os.path.exists("gcp_onboard"): os.system("rm -rf gcp_onboard")
    if os.path.exists("on-board.py"): os.system("rm -rf on-board.py")
elif cloud == 2:
    if os.path.exists("onboard_script"): os.system("rm -rf onboard_script")
    os.system(f"git clone --sparse --depth=1 https://{centralizedpat}@dev.azure.com/nsitmspdevops/Insight%20CMP%20Centralized%20Repository/_git/onboard_script")
    # os.system(f"git clone --sparse --depth=1 https://{centralizedpat}@dev.azure.com/nsitmspdevops/Development-Insight%20CMP%20Centralized%20Repository/_git/onboard_script")
    cwd_home = os.getcwd()
    os.chdir(f"{cwd_home}/onboard_script")
    if os.path.exists("azure-pipelines.yml"): os.system("rm azure-pipelines.yml")
    if os.path.exists("azure.py"): os.system("rm azure.py")
    if os.path.exists("gcp.py"): os.system("rm gcp.py")
    exec(open("aws.py").read()) 
    os.chdir(f"{cwd_home}")
    if os.path.exists("onboard_script"): os.system("rm -rf onboard_script")
    if os.path.exists("azure_onboard"): os.system("rm -rf azure_onboard")
    if os.path.exists("aws_onboard"): os.system("rm -rf aws_onboard")
    if os.path.exists("gcp_onboard"): os.system("rm -rf gcp_onboard")
    if os.path.exists("on-board.py"): os.system("rm -rf on-board.py")
elif cloud == 3:
    if os.path.exists("onboard_script"): os.system("rm -rf onboard_script")
    os.system(f"git clone --sparse --depth=1 https://{centralizedpat}@dev.azure.com/nsitmspdevops/Insight%20CMP%20Centralized%20Repository/_git/onboard_script") 
    # os.system(f"git clone --sparse --depth=1 https://{centralizedpat}@dev.azure.com/nsitmspdevops/Development-Insight%20CMP%20Centralized%20Repository/_git/onboard_script")
    cwd_home = os.getcwd()
    os.chdir(f"{cwd_home}/onboard_script")
    if os.path.exists("azure-pipelines.yml"): os.system("rm azure-pipelines.yml")
    if os.path.exists("azure.py"): os.system("rm azure.py")
    if os.path.exists("aws.py"): os.system("rm aws.py")
    exec(open("gcp.py").read())
    os.chdir(f"{cwd_home}")
    if os.path.exists("onboard_script"): os.system("rm -rf onboard_script")
    if os.path.exists("azure_onboard"): os.system("rm -rf azure_onboard")
    if os.path.exists("aws_onboard"): os.system("rm -rf aws_onboard")
    if os.path.exists("gcp_onboard"): os.system("rm -rf gcp_onboard")
    if os.path.exists("on-board.py"): os.system("rm -rf on-board.py")
else:
    print("Wrong input received...")
    if os.path.exists("onboard_script"): os.system("rm -rf onboard_script")
    if os.path.exists("azure_onboard"): os.system("rm -rf azure_onboard")
    if os.path.exists("aws_onboard"): os.system("rm -rf aws_onboard")
    if os.path.exists("gcp_onboard"): os.system("rm -rf gcp_onboard")
    if os.path.exists("on-board.py"): os.system("rm -rf on-board.py")
